spring:
  application:
    name: BackendApp

  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb+srv://Shreyansh:Pass123@cluster0.hlz9zmj.mongodb.net/?appName=Cluster0
      database: PlaceDetailsDatabase

    redis:
      host: redis-10997.c8.us-east-1-2.ec2.cloud.redislabs.com
      port: 10997
      password: eHbdnxuc9Op6zOhgWUHetFXmK94ViIE0

server:
  port: 8050

urls:
  GmapsUrl: https://google-map-places.p.rapidapi.com/maps/api/

apiKeys:
  RapidApiKey: 3bcdc52d2fmsh64ff81232286e3ep1ba041jsnbe74ce05c134